
title: Knowledge of the Ancients
description: An exploration text game for the web.
repository: groboclown/kota

# Site Content Details
theme: jekyll-theme-slate
paginate: 10
paginate_path: "/site/blog/page:num/"
# Eventually, when there's something to download, this can change.
show_downloads: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - src
  - data
  - experimental
