
title: Knowledge of the Ancients
description: An exploration text game for the web.
repository: groboclown/kota

# Site Content Details
theme: jekyll-theme-slate
# Eventually, when there's something to download, this can change.
show_downloads: false

# Newer paginate v2 stuff, which Github doesn't support.
#pagination:
#  enabled: true
#  per_page: 10
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
#autopages:
#  enabled: true
#  categories:
#    layouts:
#      - 'autopage_category.html'
#    title: ':cat'
#    permalink: '/blog/category/:cat'
#  collections:
#    layouts:
#      - 'autopage_collection.html'
#    title: ':coll'
#    permalink: '/blog/collection/:cat'
#  tags:
#    layouts:
#      - 'autopage_collections_tags.html'
#    title: ':tag'
#    permalink: '/blog/tag/:cat'

# Older, crummy pagination stuff.
paginate: 5
paginate_path: "site/blog/page:num"


gems:
  #- jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-feed

plugins:
  #- jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - src
  - data
  - experimental
  - docs
